<%-- 
Name: Andy Stiles
Class: CSD-430 Server Side Development
Assignment: Module 7 - Project Part 2 (CREATE)
Date: 10/12/2025
File: addMovieForm.jsp
Purpose: Presents an HTML form to gather input for a new movie record. 
         Primary key is auto generated by the database.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Add Movie</title>
  <link rel="stylesheet" href="assets/styles.css" />
</head>
<body>
<header>
  <h1>Add a Movie</h1>
  <p class="subtitle">Fill out the fields. ID will be assigned by the database.</p>
</header>

<section class="desc">
  <h2>Field descriptions</h2>
  <ul>
    <li><strong>Title</strong>, <strong>Year</strong>, <strong>Genre</strong>, <strong>Director</strong>, <strong>Rating</strong>, and <strong>Notes</strong>.</li>
  </ul>
</section>

<section>
  <form class="card" action="addMovie.jsp" method="post" style="max-width:640px;">
    <label>Title*
      <input type="text" name="title" required />
    </label>

    <div class="grid">
      <label>Year*
        <input type="number" name="releaseYear" min="1888" max="2100" required />
      </label>

      <label>Genre*
        <input type="text" name="genre" required />
      </label>
    </div>

    <label>Director*
      <input type="text" name="director" required />
    </label>

    <label>Rating
      <input type="number" name="rating" step="0.1" min="0" max="10" />
    </label>

    <label>Notes
      <textarea name="notes" rows="3" placeholder="Optional short note"></textarea>
    </label>

    <div class="actions" style="margin-top:10px;">
      <button type="submit">Save Movie</button>
      <a class="button" href="/moviesdb/read.jsp">Back to Full List</a>
    </div>
  </form>
</section>

<footer>
  <p>CSD-430 - Andy Stiles - Module 7 - CREATE</p>
</footer>
</body>
</html>
